### ISSUE TITLE
Airlines dataset demo

### ISSUE THREAD

**Issue by dmorales-stratio** [Stratio/flume-ingestion#59]
http://www.stat.purdue.edu/~sguha/rhipe/doc/html/airline.html

Source: spoolDir
Sink: ElasticSearch
Dashboard: Kibana4

**Comment by dmorales-stratio** [comment]
Is this issue a work in progress or is it already finished?

**Comment by dmorales-stratio** [comment]
Please, add some captures to the docs

http://docs.stratio.com/modules/flume-ingestion/development/airlines-map-demo.html

**Comment by mariomgal** [comment]
Sorry, it's already finished. I'll close it and update the docs today.

On Tue, Aug 11, 2015 at 10:06 AM, David Morales <notifications@github.com>
wrote:

> Please, add some captures to the docs
>
>
> http://docs.stratio.com/modules/flume-ingestion/development/airlines-map-demo.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Stratio/flume-ingestion/issues/59#issuecomment-129753753>
> .
>



-- 
Mario Muñoz


Vía de las dos Castillas, 33 - Ática 4, 2ª Planta
28224 Pozuelo de Alarcón, Madrid
Tel: 91 352 59 42 // @paradigmate
