### ISSUE TITLE
Stratio Ingestion does not sent data by Kafka Sink

### ISSUE THREAD

**Issue by raulsaeztapia** [Stratio/flume-ingestion#63]
I have downloaded the Stratio Ingestion docker **stratio/ingestion** and I have tried configure for **Stratio Kafka Sink**.

When I run the *kafka consumer*, in other docker with **kafka_2.8.0-0.8.1.1**, it's consuming each message sent by **Stratio Ingestion** but show **{}** for each one.

* If I configure **file_roll**, it's writing all messages successfully
* If I configure **Flume Kafka Sink**, *kafka consumer* is consuming and showing all messages successfully

**Comment by gasparms** [comment]
How did you set up your flume agent? Paste your flume-conf.properties and explain what you want to do (or approx.).

**Comment by gasparms** [comment]
I think that you didn't configure writeBody field.  We usually work with event headers so default behavior is build a json of headers.  If you want to write body you have to configure

agent.sink.kafkaSink.writeBody = true
