### ISSUE TITLE
 Flume Ingestion Build Issue (Target folder is not created)

### ISSUE THREAD

**Issue by austindsouza** [Stratio/flume-ingestion#64]
As per the latest commit in Stratio Flume Ingestion, I tried to build the project by cloning it from GitHub repository by using the command

mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -f stratio-ingestion-dist/pom.xml

The Build is Successful, but i am not getting the target folder inside the stratio-ingestion-dist folder where the distribution file will be available. 

I am using CentOS-7 and my java -Version is 1.7.0_72

While building I got some Warning messages like

[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.stratio.ingestion:stratio-ingestion-dist:pom:0.4.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.rat:apache-rat-plugin is missing. @ com.stratio.ingestion:stratio-ingestion-parent:0.4.0-SNAPSHOT, /home/tg1/Music/Stratio/flume-ingestion/pom.xml, line 304, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 

[WARNING] Unknown file extension: /home/tg1/Documents/Stratio/flume-ingestion/stratio-ingestion-dist/src/main/unix/scripts/post
[WARNING] Unknown file extension: /home/tg1/Documents/Stratio/flume-ingestion/stratio-ingestion-dist/src/main/unix/scripts/postinst

[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ stratio-ingestion-dist ---
[INFO] Installing /home/tg1/Documents/Stratio/flume-ingestion/stratio-ingestion-dist/pom.xml to /root/.m2/repository/com/stratio/ingestion/stratio-ingestion-dist/0.4.0-SNAPSHOT/stratio-ingestion-dist-0.4.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:43 min
[INFO] Finished at: 2015-05-11T13:33:20+05:30
[INFO] Final Memory: 27M/136M

Actually my colleague is writing data into the kafka topic,
I wanted to read that topic through Flume ingestion and sink that data into Stratio Streaming CEP Engine.

Please help me to Solve this issue.

Thank you.

**Comment by epeinado** [comment]
Hi austin!

We have added a new profile in order to build the project. Can you try to add -Ppackage in your maven command?

**Comment by epeinado** [comment]
Hi Austin,

Did it work?

**Comment by austindsouza** [comment]
Hi Esther Peinado,

Yes, It worked fine

Thanks,
Austin
