### ISSUE TITLE
Artifacts could not be resolved.

### ISSUE THREAD

**Issue by anavidad3** [Stratio/flume-ingestion#67]
When I try to generate the distribution I get the next maven error:

[ERROR] Failed to execute goal on project stratio-ingestion-dist: Could not resolve dependencies for project com.stratio.ingestion:stratio-ingestion-dist:pom:0.5.0-SNAPSHOT: The following artifacts could not be resolved: com.stratio.ingestion:stratio-rest-source:jar:0.5.0-SNAPSHOT, com.stratio.ingestion:stratio-snmptraps-source:jar:0.5.0-SNAPSHOT, com.stratio.ingestion:stratio-cassandra-sink:jar:0.5.0-SNAPSHOT, com.stratio.ingestion:stratio-checkpointfilter-morphline:jar:0.5.0-SNAPSHOT, com.stratio.ingestion:stratio-commons-morphline:jar:0.5.0-SNAPSHOT, com.stratio.ingestion:stratio-druid-sink:jar:0.5.0-SNAPSHOT, com.stratio.ingestion:stratio-elasticsearch-serializer:jar:0.5.0-SNAPSHOT, com.stratio.ingestion:stratio-geoip-morphline:jar:0.5.0-SNAPSHOT, com.stratio.ingestion:stratio-geolocateairport-morphline:jar:0.5.0-SNAPSHOT, com.stratio.ingestion:stratio-irc-source:jar:0.5.0-SNAPSHOT, com.stratio.ingestion:stratio-jdbc-sink:jar:0.5.0-SNAPSHOT, com.stratio.ingestion:stratio-kafka-sink:jar:0.5.0-SNAPSHOT, com.stratio.ingestion:stratio-mongodb-sink:jar:0.5.0-SNAPSHOT, com.stratio.ingestion:stratio-nlp-morphline:jar:0.5.0-SNAPSHOT, com.stratio.ingestion:stratio-redis-source:jar:0.5.0-SNAPSHOT, com.stratio.ingestion:stratio-stratiostreaming-sink:jar:0.5.0-SNAPSHOT, com.stratio.ingestion:stratio-wikipediacleaner-morphline:jar:0.5.0-SNAPSHOT, com.stratio.ingestion:stratio-xmlxpath-deserializer:jar:0.5.0-SNAPSHOT: Could not find artifact com.stratio.ingestion:stratio-rest-source:jar:0.5.0-SNAPSHOT -> [Help 1]

These are the steps I follow:

1) git clone https://github.com/anavidad3/flume-ingestion.git 
2) cd flume-ingestion
3) git submodule init
4) git submodule update
5) cd stratio-ingestion-dist
6) mvn clean compile package -Ppackage

I have jdk  1.7.0_65 and Apache Maven 3.2.3

**Comment by epeinado** [comment]
Hi anavidada3,

Can you try to execute "mvn clean install" from parent directory before to package?
We will update documentacion to add this issue.

**Comment by anavidad3** [comment]
Hi epeinado,

It worked fine.

Thanks a lot.
