### ISSUE TITLE
Sandbox is not running on Windows10

### ISSUE THREAD

**Issue by dmorales-stratio** [Stratio/flume-ingestion#73]
Due to an issue in virtualbox, sandbox could not install the network interfaces.

https://github.com/mitchellh/vagrant/issues/6059

There is an official workaround. Just downloand and run as administrator

https://www.virtualbox.org/attachment/ticket/14040/VBox-Win10-fix-14040.exe

Let the fix run in the backgound while executing vagrant up.

That should be included in the documentation

**Comment by aargomaniz** [comment]
The module documentation has been updated with a reference to this workaround:
http://docs.stratio.com/modules/flume-ingestion/development/apache-logs-demo.html
http://docs.stratio.com/modules/flume-ingestion/development/airlines-map-demo.html
